name: Linting and Testing
on:
  push:
    branches: [main, csipaus.org/ns/v1.3-beta/storage]
  pull_request:
    branches: [main, csipaus.org/ns/v1.3-beta/storage]
  workflow_dispatch:

jobs:
  bandit_py312:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install .[dev]

      - name: Run bandit
        run: |
          bandit -r -c pyproject.toml .

  flake8_py312:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.12"

      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: Lint with flake8
        if: always()
        run: |
          pip install flake8
          flake8 . --count --statistics

  black_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

  mypy_py312:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install .[dev]

      - name: Add mypy annotator
        uses: pr-annotators/mypy-pr-annotator@v1.0.0

      - name: Run mypy
        run: |
          mypy .

  
  pytest_py312:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install .[test]

      - name: Run Pytest
        run: |
          pytest --junit-xml=.test_report.xml
      - name: Upload Results
        uses: test-summary/action@v1
        with:
          paths: .test_report.xml
        if: always()

  
